AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/diagrammer/html_renderer.rb"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ParameterLists:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false
